### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by Kaleidosium** [felixjones/gbaplusplus#14]
Hi, I know this may have come out of nowhere, but I prefer if my questions are publicly asked instead of by email where nobody else than me can see it, I have 3 questions.

1.  How much of the C++ STL will be used?
2. I saw from Twitter that you're joining Mojang, Is this the reason why you haven't been able to work on side projects including this once, and will you return to it in your free time?
3. Will this use C++ Modules once C++20 comes out?

You can close this Issue after you've answered, I'm honestly really looking forward to this as I've been looking for a good library to make GBA games that actually cares about the hardware but isn't a mess to work with.

**Comment by felixjones** [comment]
The Christmas holidays, combined with me moving to Stockholm for Mojang (starting January, still in the process of sorting this stuff out) has pretty much prevented me from writing a single line of code since the first week of December, however this project is still very much at the forefront of my hobby developments (it is an evening and weekend project) so the moment I'm set up at Mojang and got my work station equipment moved over I'll be back on this once again.

In terms of C++ STL, this is still open for discussion and I'd be interested to hear your thoughts on this aspect - I've been pretty much surveying devs every now and then to see their opinion on STL in library projects.

The **current** approach is to always leave room for STL, try not to replace STL and try not to depend on STL. Containers in particular is something I personally feel would be out of scope for re-implementing, but this opinion may likely change (discontinuous data could be a good reason for changing this stance: OAM matrices).

The C++20 features in use right now are pretty much there as a personal exploration of the standard and to pretty much make the code look pretty. I imagine the situation will be that once everything in this library gets nailed down we'll be back-porting to earlier C++ versions (I'm not 100% convinced there's good motivation to do this, but I feel it may be a way to prove code health).

I still don't know how this will be packaged up in the end, everything could end up compiled into a single include header - in which case there's little reason to avoid modules as an option. I have noted that each time I go ahead and add a compile object I end up removing it when a more appropriate generalised template version comes to mind, so if this trend continues the library could stay header-only and I see that as a very easy candidate for modules (utilising them as a standardised form of pre-compiled header).

You can catch me on the GBDev Discord: https://discordapp.com/invite/gpBxq85 (I am Xilefian#3148).

I believe when I last left the code on my end I was writing a fixed point arithmetic implementation (which I dislike doing considering there's so many existing solutions to this out there).

As a personal comment on "actually cares about the hardware but isn't a mess to work with" indeed the motivation has always been to do exactly what the existing C GBA libraries achieve but with a bit more power and less assumptions. I was never happy with the enforced chunk of IWRAM/EWRAM consumed by libgba or libtonc and the way you were forced to use their IRQ handler - however I am forever understanding of the familiarity of the existing libraries and their popular tutorials so having the option to bring in familiar keywords (such as `static auto& DISPCNT = gba::io::display::control;` to create DISPCNT, which appears in existing online documentation) I feel makes this the "right" way to get modern C++ into GBA. I've also inspected a handful of other C++ GBA libraries and they swing very far into the realm of being game engines or SDL re-implementations and end up committing all the sins of the original C libraries, plus more, so I am quite satisfied with the goals and direction of this library for now.

**Comment by Kaleidosium** [comment]
I feel like your current approach to the STL (Not depend on it but not replace it) is the best one, many libraries depend on STL, and not everyone really likes the STL. Your header file only approach maybe is the best, I was just asking since some Modern C++ libraries are transitioning to that since it apparently has faster compile times. thanks for the response.

**Comment by felixjones** [comment]
I think "not liking STL" is becoming less and less of a good reason to avoid it as the years go by.
STL is used in some places, but I'm restricting it to compile-time only as much as possible (type_traits as an example).

I find it's often STL containers that people have complaints about - and I am sympathetic to that in the case of the GBA, so the philosophy is more specific to STL containers than any other part.

This might change for an implementation of debug print where C++ string containers may actually be a good idea, but will cross that bridge when we get there (I'm somewhat a fan of std::string_view, so I imagine I'd first try and enforce only using std::string_view in this particular example).

I do actually write my test apps using STL containers, just for the fun of having them available and using custom allocators (std::vector into VRAM is rather neat).

Will close this as the 3 questions are answered. If we should discuss the scope of STL it should probably be its own on-going issue whilst everything is in early days so we can assess it periodically.
